name: Main

on:
    push:
    pull_request: 
    workflow_dispatch: 

permissions: write-all

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Default metrics
              uses: lowlighter/metrics@latest
              with:
                filename: metrics.base.svg
                token: ${{ secrets.METRICS_TOKEN }}
                base: header, activity, community, repositories, metadata
